class_path: datamodules.mime_datamodule.ImagesDataModule
multimodal_tokenizer_class_or_path: ???
rc_tokenizer_class_or_path: ???
frcnn_class_or_path: ???
num_workers: 4
batch_size: 16
shuffle_train: true